import { getAssetTypeFromResource } from '../processing.js';
// Generated by CodiumAI

describe('getAssetTypeFromResource', () => {
    // Returns 'media' for a resource with a media file extension
    it('should return "media" when the resource has a media file extension', () => {
        const resource = {
            name: 'example.mp4',
            initiatorType: 'fetch',
        };

        const result = getAssetTypeFromResource(resource);

        expect(result).toBe('media');
    });

    // Returns 'image' for a resource with an image file extension
    it('should return "image" when the resource has an image file extension', () => {
        const resource = {
            name: 'example.jpg',
            initiatorType: 'img',
        };

        const result = getAssetTypeFromResource(resource);

        expect(result).toBe('image');
    });

    // Returns 'font' for a resource with a font file extension
    it('should return "font" when the resource has a font file extension', () => {
        const resource = {
            name: 'example.woff',
            initiatorType: 'link',
        };

        const result = getAssetTypeFromResource(resource);

        expect(result).toBe('font');
    });

    // Returns 'unknown' for a resource with no file extension
    it('should return "unknown" when the resource has no file extension', () => {
        const resource = {
            name: 'example',
            initiatorType: 'link',
        };

        const result = getAssetTypeFromResource(resource);

        expect(result).toBe('unknown');
    });

    // Returns 'unknown' for a resource with an unknown file extension
    it('should return "unknown" when the resource has an unknown file extension', () => {
        const resource = {
            name: 'example.xyz',
            initiatorType: 'link',
        };

        const result = getAssetTypeFromResource(resource);

        expect(result).toBe('unknown');
    });
});
