// Generated by CodiumAI
import { calculateAverageFromArray } from '../../analysis/statistics.js';

describe('calculateAverageFromArray', () => {
    // Test with an array of positive integers
    it('should calculate the average correctly when given an array of positive integers', () => {
        const array = [1, 2, 3, 4, 5];
        const result = calculateAverageFromArray(array);
        expect(result).toBe(3);
    });

    // Test with an array of negative integers
    it('should calculate the average correctly when given an array of negative integers', () => {
        const array = [-1, -2, -3, -4, -5];
        const result = calculateAverageFromArray(array);
        expect(result).toBe(-3);
    });

    // Test with an array of mixed positive and negative integers
    it('should calculate the average correctly when given an array of mixed positive and negative integers', () => {
        const array = [-1, 2, -3, 4, -5];
        const result = calculateAverageFromArray(array);
        expect(result).toBe(-0.6);
    });

    // Test with an empty array
    it('should return null when given an empty array', () => {
        const array = [];
        const result = calculateAverageFromArray(array);
        expect(result).toBe(null);
    });

    // Test with an array containing only one element
    it('should return the same value as the single element when given an array containing only one element', () => {
        const array = [5];
        const result = calculateAverageFromArray(array);
        expect(result).toBe(5);
    });
});
